### ISSUE TITLE
First Session 2nd Week

### ISSUE THREAD

**Issue by idgm5** [ghamtre/HTMLForms#2]

**Comment by ferbaco86** [comment]
- Next time  don't forget to read carefully the requirements of the project

- Consider the impact on loading time when using the ">" CSS selector

**Comment by harshdeepkanhai-zz** [comment]
* Add CSS variables to reduce the code duplicity for colors and other repeatable things,
* See this for reference [CSS3 var()](https://www.w3schools.com/css/css3_variables.asp)

**Comment by idgm5** [comment]
Thank you for your advice guys!

We'll take it into consideration once our project is approved.
